# Generated by Django 5.1.4 on 2024-12-13 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('tile_image', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date to publish')),
            ],
        ),
        migrations.CreateModel(
            name='Article_Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('tile_image', models.CharField(max_length=200)),
                ('sort_order', models.IntegerField(default=9999)),
                ('pub_date', models.DateTimeField(verbose_name='date to publish')),
            ],
        ),
        migrations.CreateModel(
            name='Article_Layout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Article_Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date to publish')),
            ],
        ),
        migrations.CreateModel(
            name='Article_Group_Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sort_order', models.IntegerField(default=9999)),
                ('pub_date', models.DateTimeField(verbose_name='date to publish')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.article')),
                ('article_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.article_group')),
            ],
        ),
        migrations.CreateModel(
            name='Article_Section_Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.article')),
                ('article_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.article_section')),
            ],
        ),
    ]
