# Generated by Django 5.1.4 on 2024-12-16 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='synopsis',
            field=models.CharField(default='Test', max_length=1000),
            preserve_default=False,
        ),
    ]
