# Generated by Django 5.1.4 on 2024-12-16 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_synopsis'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='blog_image',
            field=models.CharField(default='/images/site-banner.jpg', max_length=200),
            preserve_default=False,
        ),
    ]
