# Generated by Django 5.1.4 on 2024-12-16 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_article_youtube_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='youtube_video',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
