# Generated by Django 5.1.4 on 2024-12-16 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_alter_article_youtube_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='article_layout',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article_section',
            name='article_layout',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='articles.article_layout'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article_section',
            name='article_section_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article_section',
            name='article_section_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='article_section_link',
            name='sort_order',
            field=models.IntegerField(default=9999),
        ),
        migrations.AlterField(
            model_name='article_layout',
            name='name',
            field=models.CharField(max_length=25),
        ),
    ]
