# Generated by Django 5.1.4 on 2024-12-16 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_article_layout_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article_section_link',
            name='pub_date',
            field=models.DateTimeField(auto_now=True, verbose_name='date to publish'),
        ),
        migrations.AlterField(
            model_name='article',
            name='blog_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='article',
            name='synopsis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='tile_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='article_group',
            name='tile_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
