# Generated by Django 5.1.4 on 2024-12-17 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_article_pub_day_article_pub_month'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='pub_day',
        ),
        migrations.RemoveField(
            model_name='article',
            name='pub_month',
        ),
    ]
