# Generated by Django 5.1.4 on 2025-01-03 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_remove_article_pub_day_remove_article_pub_month'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-pub_date']},
        ),
        migrations.AddField(
            model_name='article',
            name='page_url',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
