# Generated by Django 5.1.4 on 2025-01-03 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_alter_article_options_article_page_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='page_url',
            field=models.SlugField(max_length=100, null=True, unique=True),
        ),
    ]
