# Generated by Django 5.1.4 on 2025-01-03 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_alter_article_page_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='page_url',
        ),
    ]
